services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      mode: replicated
      replicas: 1

  postgres:
    image: postgres:latest
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "fintech"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - postgres:/var/lib/postgresql

  redis-compose:
    image: redis
    command: redis-server
    container_name: redis
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "6379:6379"

  opentelemetry:
    image: otel/opentelemetry-collector-dev:latest
    container_name: opentelemetry
    ports:
      - "4317:4317"
      - "55680:55680"

  ledger-app:
    container_name: "ledger-app"
    build:
      context: /backend/ledger
      dockerfile: Dockerfile
    image: ledger-app
    depends_on:
      - opentelemetry
      - rabbitmq
      - postgres
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - /backend/ledger/.env
    ports:
      - "8080:8080"

  reconsiliation-api:
    container_name: "reconsiliation-api"
    build:
      context: ./backend/reconsiliation
      dockerfile: Dockerfile
    image: reconsiliation-app
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - /backend/reconsiliation/.env
    ports:
      - "8081:8080"
    entrypoint: ["/reconsiliation-api"]

  reconsiliation-consumer:
    container_name: "reconsiliation-consumer"
    build:
      context: ./backend/reconsiliation
      dockerfile: Dockerfile
    image: reconsiliation-app
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - /backend/reconsiliation/.env
    entrypoint: ["/reconsiliation-consumer"]

  frontend-app:
    container_name: "frontend-app"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - ledger-app
      - reconsiliation-api

volumes:
  postgres:
